language: node_js
sudo: false
env:
  matrix:
  - CXX=g++-4.8
  - secure: wGxV8QYRP2embP0Br0xjteFNfFqJhFkldFx68Iu0qtz72SoOCSYRgzPSHm6uEX5SYJS7VMssVSCpygkj9uhgDWBWKKyfUHsWtJc0U3ggP0JDSqV/LW2fQQ9kMDmKgfKO0+zPY+qCWmK4PHdJvjI+3UktIp3VssuUuqIGesB8zaR/guJShyPkbl+GZ5zhuOTi5FEVhhhmwTVQpePSNrrjDogk2f4zzji+9jw6iJiS1fXZHu4PLLg3MuR7OAV3PQAA3rSoV0h/SBVhO7pmIYOiHzbto40Oj9sW4uGzVQy5nGdNxhnx2xZxXpGe/+lju/pL/4wiu0dlwkz8cJD4/HIOGIaeF2cB4Amk4hqcAtCb6VxSbWOBmGgvW+ec2/uWu1uxo12Q323PNVB/55d9mX/c+kPEFZgOIXcTD3GxOh0DHyLO40g8QuAOeffSAsyYvSvLcyYML+ZNAZqiW5X/UtZoH6nWUau1YO2Hy9xJxlOV8ZSWpBtuhrn/LDhsWI6GED6lE/m18RkK/s0cU1qCswPjZwL124PINAx045i+/USk9pvd0Dwn5P0fW48+E/0/8ncqr8iu6r4zWhuE1RZ1ibrh++6s12aZtqJG0+GX6kCH68cWD7OuF0u6KnmSTCVX5SBSbojJHdN9lWrRHOk03yjaIrc2XHS4l8CO49FvIpUHki0=
  - secure: VGuRRH731FXaki70FC+oQAUgZBzjgoHUDXhyGoeW2PmSO20UABdXU+JruqgZP5VLw4J0qjWo4wlXFqZeGLo6n7GQ7EZPSBezTFP3FB3ibY96fXR5zHw0rop1fCG+8m+bMeeBEgF4QFEM5F9/0xJ/yrahsCESv0fn6bqeAfbx9XIDx/W+IjNMY8u6IhD1Xf7plK+iHOSYbxXv+FNbNXkhcJy1YIpfGYZ+lUP2IUhWxBNuq05VRrvrxjWI4U6cLsi1FkSWr90//LY3aDBGhdzD2ymrut45YKPoQPypf/mS/teDl2CgO6mZ4Cz2dKWBRVoqJ+Q6hWJpGGXtuBzdcEVpYreTJQku5PCDryaaSoUX7nPtW/FkD6mrSa2efSFXibnZtYK2/jHmDg6MNcjdFcY0Oc/rwjGLAnQ3MGoMqPhS6lAx5NFf3lAXxDwEXoD6SEIsGfvNxMk0pabfGT9SvDA+FQ36Vx5mRjfDVHiWBeziyNfkR588ORZZOSIXPrCWE99xel8B2cgexE/SOg4rr+Rvr9ohqzbjhe+si84WpRwpFfX11K8l75z5HIRQOx7+KyjDbw3fT24Xked2oTisV91KudOcZEuqfop99NhzZ290+2+NDQBUWmICmkaRKFlcz+LBZIu8pLqdYEu/PeZtZsdL563UAnOZl87l61vnYR9tWow=
  - secure: hFHp1XxdxcTARPb8EqMVhsKL7t3N8x9kE/XWjfjQXEQiuWg3q6wBhg0ilQIOD4PFYbYBYjTXNYBwYCLtGax+p9x8xfqvGdY+9q7cRXa2MjYExBBZ6AUBu9TzYM/t0ndHqJQjp6Y5kZuQCR6iJaAfaYCJ5i9hQTZ/DbjP31U0RCxknJndtsebq9zkr6GgLHHZiC6zDLWgmwrR22d+TvCTT7qggcyH2Pk5nmVEoDxy7RtL0kJEk7omHfvaYwpHhuuN0GJ8yLJN/+3wZFN3tF46NzQzHGrd5sq6JGq71tFUGWGxaZHMZj1xYwBNn7e/cT5+YUd0NMBZtCjFtDEFarlUdOZUwNR6l8f+ykRv1KJDZwVdLson1Z3r83nvibbzajQMMV3D4lR+IlXC5c0xtg9/emdau8jvwNG468JSFiCtlFO8RJ9MhLar9zK4idIXwomfPLsNsYiRoXwLvFHokAc7H7R1gmN+6P2lR77UeTjlw6H4nQcsw6M5ZhDHewjkBHItELc+uEi6akIu1iwFJCRLJHReatGAie8Zemt8GZ0doapbrvlAZOGTANPaIVEzDKM4yo0CiGfMzZLMVPcTTo5Iymdshqd7Z7E3EJ/n9iMLc4qLDIupAnCPgNTgCQD0hxIWM7licdlEbnSVysf/xtDWLuxuyMvRqpXU/s9JbIH3nMA=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
services:
- mongodb
before_install:
- export SECRET_KEY=[$SECRET_KEY]
- export SMTP_PASSWORD=[$SMTP_PASSWORD]
- export ADMIN_PASSWORD=[$ADMIN_PASSWORD]
- node --version | grep -q 'v0.8' && npm install -g npm@3.3.12 || true
node_js:
- 5.4.1
notifications:
  email: false
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
