language: node_js
sudo: false
env:
  matrix:
  - CXX=g++-4.8
  - password=fanky2010
  global:
  - secure: zMlnnX543K5qiUhV4keW4KkcL16h1s6oVdSrpwHrGbrdUgLVe5h7mXvm0EXb6t+KI7OjXDy1xQRbW1OgMhtDpV3Rn5H3WKQtPLGpHG3h4kkGlKToDQe7/Ns1liPzxFw/tBjL0WNHreuP/93fkABBYini6xEcmTDrOuFI/V3Zk7fYil2x24h688stMsSFdqiL3OyywMFXC5CVwKjvXAfH80/E6na2lKB42aXldXlLiCSapM76VTOg8FTuSClhlmN0r2iBv4NVIbv0sHMMozeOkr2KdMDoVs8dkMHzxJifiqGawBL6EauhDOjmsuYOPyeA0BfL29zf8TYdKYdPsZ0PZHo3yFMQY6ViGM8poa0aJOfkySLwRZNaaxHP8vfduGjqSJ+i/Sku8BHeM7gDSE2cd4sW9g/34QIx9OMs4wCGF4FkBqff7quKxL0G4ki2owqnBQlkQG5Q0MmZx9XrtDSVGXd6Qz/oDIYDtf2n1OYelfCpNcylT05d3zyJ1FVfd94Qqp1w9hq4uLKMQT2nSYPtQ1H6KayjNJh9zs71RybewOz9Kn2snKmWxNDBTbDtOcQPRi/NgJG948a0tYTjGLEG+18x1IKtRfP0bIdaFOm7szsLFAFPpKogXT+KaIYO3oy4YwTgTPPzCd4Ztszao8KPuFjC7L6aYOgi9qJAaUsUcM8=
  - secure: Z9vcU/OAt/3tw3tnHOY8aQDDf9ADiRKMaFjhV/xvCM/5LZCZnxis1JZs4d16eY/Pp5E7oI3kJNFmjfL+EYkPpHWVgmOTRYzz5UFJxmE8drV32KwCCwQXYMHj0nQ3Ym+F+JEFhdJShFlWxrYdtL6H4dBofiaJe4w2WoEgQSk0kpZ/34TPD+0Kxr2mERYgb59ahxTT2bH2rn236TXvPhli/K0pfM8fMFi+s7Ew3N1AnpcsiyAOE9JL9tFSNcQo50QJGb0P038GqfvsT+8Iog6tBobf/p9Log06MQmMzthkz10VXf8vRXpokJTh8oLrzVnzqF7mHY1U/BEBlvEo6ivjdIzguHgwJd4B8ScFEvepXhrC2dPGhtrJS9M9T4gbSuPAWHtNNzShBChEq5xelp5loLpLHDXxJKMnF88B1Ywx2TMcOjAdQLfzhHvARH9YrL8dFDNCaODnvJxekI1rpjDnKEFsuwOB81rdDj/XL/wRjMIOoiYgyOg7GZG6bMJqmecXxQFDa2KdchIIeFXEJ9YP5c2FQPV+6xKj9FfnZS8vP48NNJecjoc3llr2N0DTJnZ2xNgKXo6jef7ED4GGq3rZFXVsVZPagpA8ZpVvnhBjhIfymsb1q+T6kxPcBU72KSxTXO5NzsV1AxYn/BXIo1ba2tacTW5+yTBHrbKdKhgex7Q=
  - secure: p4nBJLyA3/ChvvQcFrh4VUltpixhbrPTr6dmlvl/lpZMNthdRMOV4KwX6aBw+d5FDKW5EqPhY2FVM3iDJgy4Zm9vlIbTN+p1ZX8dsZt1T9znxDRhrwyLKAhP0Pf0Cq6IzGZe8FfbVXODB+YTc4AzZNU9XdoXcVt4voFRZpuwvfrZo+9YVIWGDNg8VPGuXTchodzDD+5mqfbxvS78c/Yh4Z08apqMonAtFmQtUwN6v3yaEsGQzfE68ROaDTjTKUt3ks4ZuahpkrbpKQa0RIqN9RyZC9z9PMNK2uRmkUwRdWc0Hd54vhSRAl8bkwITsnk37uoAtbE1L9XzjxMU758hEy5yEhe+HOp8l+hg6GuIipiiL2Fy3+t0oV0lDEqVxTcD9FjPVZEXwfjMNPHx8m9lJ6K7Nyz3FpKyf9SSg4o1YREmr3ynjkDB6Xw0aGrDcvx+O3UkNlEUbAZxpGvKfgc5t7/HxunRCvySFLRkwO13jAeuH8pJnLBV918QZefnjodTVJu//l56qqYyj6GNWZFom1svrCdUFnSqXi17iP6iQpxsrSV/Ow/beJSbqhnw50C/s1KHvePcXS0gnGqSoW9Utnju33gKdcjkvfn4TUXqIDsCAM4AekJBHLTalBs49fZ64+v6ZmkgHlFUNn/dIeWbrGXISFPEmxF++91lOgehTjo=
script:
    - export SECRET_KEY=$app:secret
    - export SMTP_PASSWORD=$smpt:password
    - export ADMIN_PASSWORD=$superAdmin:password
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
services:
- mongodb
before_install:
- node --version | grep -q 'v0.8' && npm install -g npm@3.3.12 || true
node_js:
- 5.4.1
notifications:
  email: false
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
