language: node_js
sudo: false
env:
  matrix:
  - CXX=g++-4.8
  global:
  - secure: Tt8y2YiooDFQrChoRUerFeI7Kl5gl5DmFSzVeMJPe1Jvqa7fTWyCuUz1vZ1GxaULRuep1awQFKsOR/k5K4a9WpcR8qAqu6gbt4V3hB/bjju/Fbz8lfPZ7Y4WGg+mo93UyK6Hfc6T2+Ph1e/q4EjncmE6ZsrbkxnjLNxioxeGBpixSHSJBVnWQ5DX5b15iYHrL6p+3deWSleRuBU5+Xiwtl9DpSszbwBX1kTVyFOKmSOcdg4Yl13/HkjO9IbHtcnOC5QbIAVgWeXymVtpCRDUw2g70idlu0RJIVr93oBXYY+1zPzXVvv4mtKitN1lY+P1szkL6tmVYscKaJDHHx9W8ytqX7gd9si5/tZXiyYa9r9SXPavezNOJ6skPnEN9l/FRmsNzNuMK6XkJwpJ2du9tTYTHn5t25FSbkv3hZQQ7lUW9XZsne1btGhSLu/+u5slc3ZLEBh5Hxpoo1gPxbiRHi1tdfefi4WCcwXKAPzTOWoy6C8EIYN9jdtKAD7GBnVrrd2HCrvC43kDHQs3AFT88vump+JAk6YwJZ9RapG9HNYD1Wv5aUxcpOmzxO11nqut9TaBB31+taUXe0slHqSOtzE2Eydy8EF8V8/iPL5pMHOfpevermKpWmIC3IvLeJNp561Z5ZmYjNlvR2IXc9Pbkk2pMkDprCdF/JVsbX6i7Zk=
  - secure: 29qrlTd8lwgn3PgHKBGCRoKfwrlB0HaaUX/VO0GXVeDYyhfqEpohBvkdkbXFUMukNkBaaMIuB9zXdFENsOElFZj1ytZIpk0rPxoPh5Yo/rpnnqA4jFQvWCvuKqJKgfp1gVKyUz5QQt7C2V38gmvWPa560ttJG1nsgLpWYekpEFLVTKc96X0ih9TRWrRiXVCmFvxck6PA/EzBlaPBNwbjObPVwxRiZo3sCgkgWcgb6eRNoXtZ6bbh0IDM0Ub71HDsK8Ic3EBETqoCWYmWfSuEPWBKPsAC28180k4/D1fiakrh50Nmwc3d0pAP3Vad5vvSM45Wd4ZreBV5Dufu0r5ORlKsKYaJpMPbRZGdcUd3riOYAoERvirL7k6m2hM62cyEAQxnQoiz32JotJ03eKOZp+08RARbeb1IeuKad5yu4f+4UNQV9ddMynKd61ffSxPY7eFIT+saX2Di2M28nErrIdDtKzQh/5aKg9gjKLn/LZ5wRQml5YFKw3EG03I4miWfvpUIq1bifd6uPGYnuDf0N79RIImMMHiADjAKJJfP8bcCelTyb8i8/nR+08+TuBGvyQn81xj4rXkBgp4xmuHgez0P1reEjy5JU1NATMCM8cxgtah3RGOOsB9owoC71sYVjjYkgCYqZSJ2WsTAotO5+Pzo4CO4kug37CFme3SZ4y4=
  - secure: zQozD8Qp+8uluxQst3nn12liTmyPtYKYplFHDNHXxV1bEykvofTwNbsOTVfXiJARUm1FX9UfLiFB7b6TpPGOKxQN3xDlUrGiRL9sI8AjKAqBlOcDNP8pKLmF5VCleiozyDOyPvrFKulxG6TJVBlDNjl7ucL7AhsHWcm3rodHlJA905fdmZ10CbcJWDnss2Jd3zxpMsLynv1YtYRwFr6WuTpc6jhV4gWUxA958a/nnMXjGe6+X96JQqAE42TnBU76K7FBzhQ4MmNTyuxQcquSFDZw7x5rTOOxRgU57PqZLaixGLXSMN3L3tF9wNhhALNd3hSgaweO8/G3jOQKpp1koDi46/keaYodbhsk4hwuxmnQHz1qheSdgjT16e8nyDNV41Yfjm/qx+YPYzXONhOMOe2ArAgpr4lqGKC3JxNXuboycWsm60T3eq4+Oe0pwFqb70DRuGJpd2J1jqfPgxRbWfa6boPtydlxiZe8xTiH+7zw4Ke69LdCzWsVIGvCnOsCISBS08jmYyZKSoqbIBJRapsnll8lYl1muITMw0pQsOW/6mBrT32qYQIDb2RPca1W8KUOC1DhdEW0gSJzoPlfHXNJFFVfupuDfXF2ILVLOaV82nO9yl8qTMSx2eok3jvM4t2jfb8Jy+tt0dhOFtFJEmZ1lg6Zu02EpZvJS/0gzto=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
services:
- mongodb
before_install:
- export SECRET_KEY=[secure]
- export SMTP_PASSWORD=[secure]
- export ADMIN_PASSWORD=[secure]
- node --version | grep -q 'v0.8' && npm install -g npm@3.3.12 || true
node_js:
- 5.4.1
notifications:
  email: false
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
