language: node_js
sudo: true
env:
  matrix:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
services:
- mongodb
before_install:
- node --version | grep -q 'v0.8' && npm install -g npm@3.3.12 || true
# Setup a wildcard local DNS for *.eworm.com
- sudo apt-get install -qq -y --force-yes dnsmasq
- echo "listen-address=127.0.0.1" | sudo tee -a /etc/dnsmasq.conf > /dev/null
- echo "bind-interfaces" | sudo tee -a /etc/dnsmasq.conf > /dev/null
- echo "address=/.eworm.com/127.0.0.1" | sudo tee -a /etc/dnsmasq.conf > /dev/null
- echo "user=root" | sudo tee -a /etc/dnsmasq.conf > /dev/null
- sudo service dnsmasq restart
node_js:
- 5.4.1
notifications:
  email: false
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
