language: node_js
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8


before_install:
  - node --version | grep -q 'v0.8' && npm install -g npm@3.3.12 || true

node_js:
  - "5.4.1"

notifications:
  email: false

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"